### ISSUE TITLE
ErrorCode:1643

### ISSUE THREAD

**Issue by ghost** [Bungie-net/api#595]
Just making sure you guys know this error is poping up now.    I'm going to add retry logic for it and hope my loaders start working again.

I got it from this call: https://www.bungie.net/platform/Destiny2/4/Profile/4611686018467657073/?components=100

{"ErrorCode":1643,"ThrottleSeconds":0,"ErrorStatus":"DestinyServiceFailure","Message":"We couldn't get your Destiny data right now, something funky's going on.  Try again later.","MessageData":{}}

**Comment by vthornheart-bng** [comment]
Hmm, is this happening just for specific users for you, intermittently, consistently?

**Comment by floatingatoll** [comment]
If you have the HTTP response headers for the error and can include them here, that could help narrow down what’s up.

**Comment by migit128** [comment]
intermittent, but frequent enough to cause problems.

I dont log the headers.

Here are some log snippets:
```
2018-08-06 14:02:26,428; [1]; INFO; - Destiny2_V1.GetStats: URL=https://www.bungie.net/platform/Destiny2/4/Account/4611686018470903386/Stats?groups=85
2018-08-06 14:02:27,037; [1]; ERROR; - APIErrorChecker.CheckErrorCode:Got an unhandled non-successful result from the bungie API.
2018-08-06 14:02:27,053; [1]; INFO; - Errored out getting Raid info.   check raid.report
BungieAPI threw an error.  
{"ErrorCode":1643,"ThrottleSeconds":0,"ErrorStatus":"DestinyServiceFailure","Message":"We couldn't get your Destiny data right now, something funky's going on.  Try again later.","MessageData":{}}
2018-08-06 14:02:27,053; [1]; INFO; - Destiny2_V1.GetStats: URL=https://www.bungie.net/platform/Destiny2/4/Account/4611686018470903386/Stats
2018-08-06 14:02:27,443; [1]; ERROR; - APIErrorChecker.CheckErrorCode:Got an unhandled non-successful result from the bungie API.
2018-08-06 14:02:27,459; [1]; INFO; - Errored out getting PVP info.  Have they even PVP'ed? check destinytracker.com 
BungieAPI threw an error.  
{"ErrorCode":1643,"ThrottleSeconds":0,"ErrorStatus":"DestinyServiceFailure","Message":"We couldn't get your Destiny data right now, something funky's going on.  Try again later.","MessageData":{}}
```

```

2018-08-06 14:01:06,297; [1]; INFO; - Destiny2_V1.GetStats: URL=https://www.bungie.net/platform/Destiny2/4/Account/4611686018467344943/Stats?groups=85
2018-08-06 14:01:06,751; [1]; ERROR; - APIErrorChecker.CheckErrorCode:Got an unhandled non-successful result from the bungie API.
2018-08-06 14:01:06,766; [1]; INFO; - Errored out getting Raid info.   check raid.report
BungieAPI threw an error.  
{"ErrorCode":1643,"ThrottleSeconds":0,"ErrorStatus":"DestinyServiceFailure","Message":"We couldn't get your Destiny data right now, something funky's going on.  Try again later.","MessageData":{}}
2018-08-06 14:01:06,766; [1]; INFO; - Destiny2_V1.GetStats: URL=https://www.bungie.net/platform/Destiny2/4/Account/4611686018467344943/Stats
2018-08-06 14:01:07,344; [1]; ERROR; - APIErrorChecker.CheckErrorCode:Got an unhandled non-successful result from the bungie API.
2018-08-06 14:01:07,344; [1]; INFO; - Errored out getting PVP info.  Have they even PVP'ed? check destinytracker.com 
BungieAPI threw an error.  
{"ErrorCode":1643,"ThrottleSeconds":0,"ErrorStatus":"DestinyServiceFailure","Message":"We couldn't get your Destiny data right now, something funky's going on.  Try again later.","MessageData":{}}
```

```
2018-08-06 14:01:04,459; [1]; INFO; - Destiny2_V1.GetStats: URL=https://www.bungie.net/platform/Destiny2/4/Account/4611686018467481266/Stats?groups=85
2018-08-06 14:01:04,834; [1]; ERROR; - APIErrorChecker.CheckErrorCode:Got an unhandled non-successful result from the bungie API.
2018-08-06 14:01:04,850; [1]; INFO; - Errored out getting Raid info.   check raid.report
BungieAPI threw an error.  
{"ErrorCode":1643,"ThrottleSeconds":0,"ErrorStatus":"DestinyServiceFailure","Message":"We couldn't get your Destiny data right now, something funky's going on.  Try again later.","MessageData":{}}
2018-08-06 14:01:04,850; [1]; INFO; - Destiny2_V1.GetStats: URL=https://www.bungie.net/platform/Destiny2/4/Account/4611686018467481266/Stats
2018-08-06 14:01:05,225; [1]; ERROR; - APIErrorChecker.CheckErrorCode:Got an unhandled non-successful result from the bungie API.
2018-08-06 14:01:05,240; [1]; INFO; - Errored out getting PVP info.  Have they even PVP'ed? check destinytracker.com 
BungieAPI threw an error.  
{"ErrorCode":1643,"ThrottleSeconds":0,"ErrorStatus":"DestinyServiceFailure","Message":"We couldn't get your Destiny data right now, something funky's going on.  Try again later.","MessageData":{}}
```

```
2018-08-06 13:04:03,356; [1]; INFO; - Destiny2_V1.GetProfile: URL=https://www.bungie.net/platform/Destiny2/4/Profile/4611686018476911933/?components=100
2018-08-06 13:04:03,700; [1]; ERROR; - APIErrorChecker.CheckErrorCode:Got an unhandled non-successful result from the bungie API.
2018-08-06 13:04:03,950; [1]; DEBUG; - Metric; Method: GetProfile; 594;(in ms)
2018-08-06 13:04:03,950; [1]; FATAL; - Uncaught Exception
BungieAPI threw an error.  
{"ErrorCode":1643,"ThrottleSeconds":0,"ErrorStatus":"DestinyServiceFailure","Message":"We couldn't get your Destiny data right now, something funky's going on.  Try again later.","MessageData":{}}
```

```
2018-08-06 15:04:36,815; [1]; INFO; - Destiny2_V1.GetProfile: URL=https://www.bungie.net/platform/Destiny2/4/Profile/4611686018467657073/?components=100
2018-08-06 15:04:37,393; [1]; ERROR; - APIErrorChecker.CheckErrorCode:Got an unhandled non-successful result from the bungie API.
2018-08-06 15:04:37,628; [1]; DEBUG; - Metric; Method: GetProfile; 817;(in ms)
2018-08-06 15:04:37,628; [1]; FATAL; - Uncaught Exception
BungieAPI threw an error.  
{"ErrorCode":1643,"ThrottleSeconds":0,"ErrorStatus":"DestinyServiceFailure","Message":"We couldn't get your Destiny data right now, something funky's going on.  Try again later.","MessageData":{}}
```

I added some retry logic (apparently it doesnt cap out at 3 retries.. woops):
```
This one was retried 13 times before being successful:
2018-08-06 15:42:24,117; [1]; INFO; - Destiny2_V1.GetStats: URL=https://www.bungie.net/platform/Destiny2/4/Account/4611686018472071151/Stats
2018-08-06 15:42:24,492; [1]; WARN; - APIErrorChecker.CheckErrorCode: ErrorCode is 1643
```

Couple retries on this on: 
```
2018-08-06 15:42:23,352; [1]; INFO; - Destiny2_V1.GetStats: URL=https://www.bungie.net/platform/Destiny2/4/Account/4611686018472071151/Stats?groups=85
2018-08-06 15:42:23,742; [1]; WARN; - APIErrorChecker.CheckErrorCode: ErrorCode is 1643
```

More on this one: 
```
2018-08-06 15:41:42,794; [1]; INFO; - Destiny2_V1.GetStats: URL=https://www.bungie.net/platform/Destiny2/4/Account/4611686018475240455/Stats
2018-08-06 15:41:43,294; [1]; WARN; - APIErrorChecker.CheckErrorCode: ErrorCode is 1643
2018-08-06 15:41:43,309; [1]; WARN; - {}
2018-08-06 15:41:43,325; [1]; DEBUG; - APIErrorChecker.HandleThrottler: CheckErrorCode returned true
2018-08-06 15:41:43,325; [1]; INFO; - Destiny2_V1.GetStats: URL=https://www.bungie.net/platform/Destiny2/4/Account/4611686018475240455/Stats
2018-08-06 15:41:43,809; [1]; WARN; - APIErrorChecker.CheckErrorCode: ErrorCode is 1643
2018-08-06 15:41:43,825; [1]; WARN; - {}
2018-08-06 15:41:43,841; [1]; DEBUG; - APIErrorChecker.HandleThrottler: CheckErrorCode returned true
2018-08-06 15:41:43,841; [1]; INFO; - Destiny2_V1.GetStats: URL=https://www.bungie.net/platform/Destiny2/4/Account/4611686018475240455/Stats
2018-08-06 15:41:44,294; [1]; WARN; - APIErrorChecker.CheckErrorCode: ErrorCode is 1643
```



Just got this one too... 
```
2018-08-06 15:39:22,899; [1]; INFO; - Destiny2_V1.GetStats: URL=https://www.bungie.net/platform/Destiny2/4/Account/4611686018475979049/Stats?groups=85
2018-08-06 15:39:23,102; [1]; ERROR; - APIErrorChecker.CheckErrorCode:Got an unhandled non-successful result from the bungie API.
2018-08-06 15:39:23,117; [1]; DEBUG; - Metric; Method: GetAllCharacters; 216;(in ms)
2018-08-06 15:39:23,117; [1]; FATAL; - Uncaught Exception
BungieAPI threw an error.  
{"ErrorCode":1618,"ThrottleSeconds":0,"ErrorStatus":"DestinyUnexpectedError","Message":"An unexpected error has occurred on Bungie's servers while trying to grab Destiny information.","MessageData":{}}
```


I can go on...  Since adding the retry logic about 30 minutes ago there have been 52 1643 errors

**Comment by floatingatoll** [comment]
Thorn, is there a specific response header that you could use to see the request in the backend logs?

**Comment by migit128** [comment]
If I need to add some code to log the headers let me know and I'll look into adding it.

**Comment by vthornheart-bng** [comment]
Oh yeah, if you happen to have the "bungled" cookie value for one of these requests, that would be very handy!

By any chance, did these start to happen around the time of the most recent patch last week?  We have been experiencing some problems further upstream since that patch, and that may be affecting us as well: this could be a useful datapoint in the analysis of that bug if that's the case!

**Comment by migit128** [comment]
This is the timestamp for the first error in my logs: 2018-08-06 13:04:03,950  (pacific time)

I'll look into logging the headers.

**Comment by migit128** [comment]
I'm logging the cookie whenever it encounters an errorcode of anything other than 1 now, so the next time it happens I'll be able to get you the bungled value.  The last time I had an error was at 2018-08-06 15:42:28,118 PT, so I'm not sure if the issue has subsided.

**Comment by vthornheart-bng** [comment]
Aye, let us know if it does happen again!  I'll keep this open for a bit just in case.

**Comment by migit128** [comment]
Got another weird error code...

```
2018-08-07 01:13:30,863; [1]; INFO; - DBLoader.LoadPVPStats: zep's turn
2018-08-07 01:13:30,863; [1]; INFO; - Destiny2_V1.GetStats: URL=https://www.bungie.net/platform/Destiny2/4/Account/4611686018468034231/Stats
2018-08-07 01:13:41,149; [1]; WARN; - QueryAPI: Errored out checking error code
2018-08-07 01:13:41,181; [1]; WARN; - System.InvalidOperationException: The given header was not found.
   at System.Net.Http.Headers.HttpHeaders.GetValues(String name)
   at APX.BungieNetAPI.BungieAPI.CommonMethods.QueryAPI(String URL, Int32 retryCount) in C:\Users\Mike-GPC\source\repos\APX_Backend\BungieNetAPI\BungieAPI\CommonMethods.cs:line 47
2018-08-07 01:13:41,196; [1]; ERROR; - APIErrorChecker.CheckErrorCode:Got an unhandled non-successful result from the bungie API.
2018-08-07 01:13:41,212; [1]; DEBUG; - Metric; Method: GetStats; 10334;(in ms)
2018-08-07 01:13:41,212; [1]; FATAL; - Uncaught Exception
BungieAPI threw an error.  
{"ErrorCode":1652,"ThrottleSeconds":0,"ErrorStatus":"DestinyShardRelayProxyTimeout","Message":"Time out during communication with the game servers.  Please try again later.","MessageData":{}}
```

The "The given header was not found." error means the Set-Cookie header wasnt in the response... so no bungled code.

**Comment by brendonshih** [comment]
I'm running into a similar issue. Trying to pull my raid report for D1 and I get the 1618 errorcode when it tries to use these two endpoints:
https://www.bungie.net/d1/Platform/Destiny/Stats/Account/2/4611686018428806653/
https://www.bungie.net/d1/Platform/Destiny/2/Account/4611686018428806653/Summary/

It succeeds on the player search, though:
https://www.bungie.net/d1/Platform/Destiny/SearchDestinyPlayer/-1/IceBloo/

Makes me wonder if CrossSave messed it up, but I know other players that use CrossSave and it works.

**Comment by vthornheart-bng** [comment]
Did you cross save and/or link a Stadia account by any chance?

We are having an issue with the D1 API where folks who linked a Stadia account can no longer pull their D1 info.  The initial bug relied on a game side fix, but in testing last week it turned out that the fix caused wider problems (i.e. no one could pull D1 info anymore), so we're holding back on releasing that until we can fix the issue.  Unfortunately, the D1 API has to take a lower priority from us vs. ongoing work at the moment, so I can't give an ETA on when we can loop back to this.

**Comment by johngrable** [comment]
Did this every go anywhere? My player search also comes back fine but the summary data shows error 1618.

https://www.bungie.net/d1/Platform/Destiny/SearchDestinyPlayer/-1/hipsterrunoff/

https://www.bungie.net/d1/Platform/Destiny/1/Account/4611686018433910129/Summary/

I have never linked Stadia but did have cross save enabled and Twitch linked.

**Comment by delphiactual** [comment]
https://github.com/Bungie-net/api/issues/1677#issuecomment-1154618444

**Comment by johngrable** [comment]
That seems to be related to the search player endpoint which isn't the endpoint I'm having problems with.
